# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
