# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profil_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
