# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profil_logo',
        ),
    ]
