# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170321_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
