# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170322_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
