# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20170331_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
