# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20170401_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='textc',
            field=models.TextField(max_length=200),
        ),
    ]
