# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20170402_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='textc',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
