# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20170404_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='textc',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
