# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bd',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
